# Generated by the gRPC Python protocol compiler plugins. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from src.genereted import engine_pb2 as engine__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in engine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PluginServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetManifest = channel.unary_unary(
                '/manifest.PluginService/GetManifest',
                request_serializer=engine__pb2.GetManifestRequest.SerializeToString,
                response_deserializer=engine__pb2.GetManifestResponse.FromString,
                _registered_method=True)
        self.FuncCall = channel.unary_unary(
                '/manifest.PluginService/FuncCall',
                request_serializer=engine__pb2.FuncCallRequest.SerializeToString,
                response_deserializer=engine__pb2.FuncCallResponse.FromString,
                _registered_method=True)


class PluginServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetManifest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FuncCall(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetManifest': grpc.unary_unary_rpc_method_handler(
                    servicer.GetManifest,
                    request_deserializer=engine__pb2.GetManifestRequest.FromString,
                    response_serializer=engine__pb2.GetManifestResponse.SerializeToString,
            ),
            'FuncCall': grpc.unary_unary_rpc_method_handler(
                    servicer.FuncCall,
                    request_deserializer=engine__pb2.FuncCallRequest.FromString,
                    response_serializer=engine__pb2.FuncCallResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'manifest.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('manifest.PluginService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PluginService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetManifest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manifest.PluginService/GetManifest',
            engine__pb2.GetManifestRequest.SerializeToString,
            engine__pb2.GetManifestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def FuncCall(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/manifest.PluginService/FuncCall',
            engine__pb2.FuncCallRequest.SerializeToString,
            engine__pb2.FuncCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
