# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: engine.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65ngine.proto\x12\x08manifest\"1\n\x0c\x41rgumentList\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.manifest.Argument\"\xae\x01\n\x08\x41rgument\x12\x13\n\tstr_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12,\n\nlist_value\x18\x05 \x01(\x0b\x32\x16.manifest.ArgumentListH\x00\x12\x13\n\tjson_data\x18\x06 \x01(\tH\x00\x42\x07\n\x05value\"F\n\x0f\x46uncCallRequest\x12\x11\n\tfunc_name\x18\x01 \x01(\t\x12 \n\x04\x61rgs\x18\x02 \x03(\x0b\x32\x12.manifest.Argument\"\x88\x01\n\x10\x46uncCallResponse\x12\x13\n\tstr_value\x18\x01 \x01(\tH\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0c\x64ouble_value\x18\x03 \x01(\x01H\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12\x13\n\tjson_data\x18\x05 \x01(\tH\x00\x42\x07\n\x05value\")\n\x12GetManifestRequest\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\"(\n\x13GetManifestResponse\x12\x11\n\tjson_data\x18\x01 \x01(\t2\x9e\x01\n\rPluginService\x12J\n\x0bGetManifest\x12\x1c.manifest.GetManifestRequest\x1a\x1d.manifest.GetManifestResponse\x12\x41\n\x08\x46uncCall\x12\x19.manifest.FuncCallRequest\x1a\x1a.manifest.FuncCallResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ARGUMENTLIST']._serialized_start=26
  _globals['_ARGUMENTLIST']._serialized_end=75
  _globals['_ARGUMENT']._serialized_start=78
  _globals['_ARGUMENT']._serialized_end=252
  _globals['_FUNCCALLREQUEST']._serialized_start=254
  _globals['_FUNCCALLREQUEST']._serialized_end=324
  _globals['_FUNCCALLRESPONSE']._serialized_start=327
  _globals['_FUNCCALLRESPONSE']._serialized_end=463
  _globals['_GETMANIFESTREQUEST']._serialized_start=465
  _globals['_GETMANIFESTREQUEST']._serialized_end=506
  _globals['_GETMANIFESTRESPONSE']._serialized_start=508
  _globals['_GETMANIFESTRESPONSE']._serialized_end=548
  _globals['_PLUGINSERVICE']._serialized_start=551
  _globals['_PLUGINSERVICE']._serialized_end=709
# @@protoc_insertion_point(module_scope)
